- name: Converge
  vars_files:
    - testing_vars.yaml
  hosts: all
  tasks:
    - name: "Include Common Role"
      include_role:
        name: "common"
    - name: "Include HomeAssistant"
      include_role:
        name: "homeassistant_role"
